'use client';
import {useState} from 'react';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {LayoutDashboard,Files,Users,ContactRound,ChartNoAxesColumn,Settings2,FileCheck2,ChevronRight,Smartphone,PanelLeft,House,UserRound,ArrowUpRight} from 'lucide-react';
import {initials} from '@/lib/domain';
import type {WorkspaceData} from '@/lib/types';
export function Brand(){return <Link className="brand" href="/dashboard" aria-label="ServiceLOGME overview"><span className="brand-symbol"><FileCheck2/></span><span>ServiceLOG<em>ME</em></span></Link>;}
const navigation=[{href:'/dashboard',label:'Overview',icon:LayoutDashboard},{href:'/service-notes',label:'Service Notes',icon:Files},{href:'/customers',label:'Customers',icon:Users},{href:'/employees',label:'Employees',icon:ContactRound},{href:'/reports',label:'Reports',icon:ChartNoAxesColumn}];
export function Shell({data,children}:{data:WorkspaceData;children:React.ReactNode}){
 const path=usePathname();const [open,setOpen]=useState(false);const field=path.startsWith('/field');const section=navigation.find(n=>path.startsWith(n.href))?.label??(path.startsWith('/settings')?'Settings':'Workspace');
 if(field)return <div className="field-body"><header className="field-topbar"><Brand/><Link className="avatar" href="/field/profile" aria-label="Your profile">{initials(data.profile.full_name)}</Link></header><main className="field-main">{children}</main><nav className="field-nav" aria-label="Field navigation">{[{href:'/field',label:'Home',icon:House},{href:'/field/service-notes',label:'Service Notes',icon:Files},{href:'/field/profile',label:'Profile',icon:UserRound}].map(n=><Link key={n.href} href={n.href} className={(n.href==='/field'?path===n.href:path.startsWith(n.href))?'active':''}><n.icon/><span>{n.label}</span></Link>)}</nav></div>;
 return <><a className="skip-link" href="#main-content">Skip to content</a>{open&&<button className="sidebar-overlay" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}<aside className={`app-sidebar ${open?'open':''}`}><div className="sidebar-brand" style={{display:'flex',alignItems:'center'}}><Brand/></div><div className="org-label"><span className="org-mark">MT</span><div><strong>{data.organization.name}</strong><small>Organization workspace</small></div></div><div className="nav-label">Workspace</div><nav className="sidebar-nav" aria-label="Main navigation">{navigation.filter(n=>data.profile.role==='ADMIN'||!['/employees','/dashboard'].includes(n.href)).map(n=><Link key={n.href} href={n.href} onClick={()=>setOpen(false)} className={`nav-item ${path.startsWith(n.href)?'active':''}`}><n.icon/><span>{n.label}</span>{n.href==='/service-notes'&&<span className="nav-count">{data.notes.length}</span>}</Link>)}</nav><div className="sidebar-bottom"><div className="sidebar-divider"/><nav className="sidebar-nav" aria-label="Workspace preferences"><Link href="/field" className="nav-item"><Smartphone/><span>Field workspace</span><ArrowUpRight size={13} style={{marginLeft:'auto'}}/></Link>{data.profile.role==='ADMIN'&&<Link href="/settings" onClick={()=>setOpen(false)} className={`nav-item ${path==='/settings'?'active':''}`}><Settings2/><span>Settings</span></Link>}</nav><div className="sidebar-user"><span className="avatar">{initials(data.profile.full_name)}</span><div><strong>{data.profile.full_name}</strong><small>{data.profile.job_title}</small></div></div></div></aside><div className="app-body"><header className="app-topbar"><div className="topbar-path"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={()=>setOpen(true)}><PanelLeft/></button><span>Workspace</span><ChevronRight/><span>{section}</span></div><div className="topbar-right"><span className="topbar-date">{new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'numeric',month:'short',year:'numeric'}).format(new Date())}</span><Link href="/field"><Smartphone/><span>Field view</span></Link><span className="avatar">{initials(data.profile.full_name)}</span></div></header><main className="app-main" id="main-content">{children}</main></div></>;
}
